require:
  - rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Style/Documentation:
  Enabled: false

ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false